// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_koletonm.Models;

namespace Mission06_koletonm.Migrations
{
    [DbContext(typeof(Mission6Context))]
    [Migration("20230221032755_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_koletonm.Models.AddMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieCategoryCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("MovieCategoryCategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Anthony Russo",
                            Edited = false,
                            LentTo = "",
                            Notes = "Best movie!",
                            Rating = "PG-13",
                            Title = "Avengers: Endgame",
                            Year = (ushort)2019
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2,
                            Director = "Mark Dindal",
                            Edited = false,
                            LentTo = "",
                            Notes = "A Classic!",
                            Rating = "G",
                            Title = "Emporer's New Groove",
                            Year = (ushort)2000
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 4,
                            Director = "Niki Caro",
                            Edited = false,
                            LentTo = "",
                            Notes = "Tragic, but so moving",
                            Rating = "PG-13",
                            Title = "The Zookeeper's Wife",
                            Year = (ushort)2017
                        });
                });

            modelBuilder.Entity("Mission06_koletonm.Models.MovieCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Mystery/Thriller"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "War"
                        });
                });

            modelBuilder.Entity("Mission06_koletonm.Models.AddMovie", b =>
                {
                    b.HasOne("Mission06_koletonm.Models.MovieCategory", "MovieCategory")
                        .WithMany()
                        .HasForeignKey("MovieCategoryCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
