// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_koletonm.Models;

namespace Mission06_koletonm.Migrations
{
    [DbContext(typeof(Mission6Context))]
    partial class Mission6ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_koletonm.Models.AddMovieResponse", b =>
                {
                    b.Property<int>("MoviesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoviesId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MoviesId = 1,
                            Category = "Action/Adventure",
                            Director = "Anthony Russo",
                            Edited = false,
                            LentTo = "",
                            Notes = "Best movie!",
                            Rating = "PG-13",
                            Title = "Avengers: Endgame",
                            Year = (ushort)2019
                        },
                        new
                        {
                            MoviesId = 2,
                            Category = "Family/Comdey",
                            Director = "Mark Dindal",
                            Edited = false,
                            LentTo = "",
                            Notes = "A Classic!",
                            Rating = "G",
                            Title = "Emporer's New Groove",
                            Year = (ushort)2000
                        },
                        new
                        {
                            MoviesId = 3,
                            Category = "War/Drama",
                            Director = "Niki Caro",
                            Edited = false,
                            LentTo = "",
                            Notes = "Tragic, but so moving",
                            Rating = "PG-13",
                            Title = "The Zookeeper's Wife",
                            Year = (ushort)2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
